[2024-08-10 12:30:43] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:44] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /wrong_endpoint HTTP/1.1" 404 None
[2024-08-10 12:30:44] [tests.test_general_api] [INFO] - Checking if status code is 404
[2024-08-10 12:30:44] [tests.test_general_api] [INFO] - Checking if error message is present in response body
[2024-08-10 12:30:44] [root] [INFO] - tests/test_general_api.py::TestGeneralAPI::test_get_nonexistent_endpoint -- PASSED --
[2024-08-10 12:30:44] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:45] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/1/ HTTP/1.1" 200 None
[2024-08-10 12:30:45] [tests.test_objects_endpoint] [INFO] - Checking if status code is 200
[2024-08-10 12:30:45] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_valid_resource_status_code -- PASSED --
[2024-08-10 12:30:45] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:46] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/1/ HTTP/1.1" 200 None
[2024-08-10 12:30:46] [tests.test_objects_endpoint] [INFO] - Checking if response body has content
[2024-08-10 12:30:46] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_valid_resource_response_body -- PASSED --
[2024-08-10 12:30:46] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:46] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/99999999999999 HTTP/1.1" 404 None
[2024-08-10 12:30:46] [tests.test_objects_endpoint] [INFO] - Checking if status code is 404
[2024-08-10 12:30:46] [tests.test_objects_endpoint] [INFO] - Checking if error message is present in response body
[2024-08-10 12:30:46] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_invalid_resource_from_valid_endpoint[99999999999999] -- PASSED --
[2024-08-10 12:30:46] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:47] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/-1 HTTP/1.1" 404 None
[2024-08-10 12:30:47] [tests.test_objects_endpoint] [INFO] - Checking if status code is 404
[2024-08-10 12:30:47] [tests.test_objects_endpoint] [INFO] - Checking if error message is present in response body
[2024-08-10 12:30:47] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_invalid_resource_from_valid_endpoint[-1] -- PASSED --
[2024-08-10 12:30:47] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:47] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/0.5 HTTP/1.1" 404 None
[2024-08-10 12:30:47] [tests.test_objects_endpoint] [INFO] - Checking if status code is 404
[2024-08-10 12:30:47] [tests.test_objects_endpoint] [INFO] - Checking if error message is present in response body
[2024-08-10 12:30:47] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_invalid_resource_from_valid_endpoint[0.5] -- PASSED --
[2024-08-10 12:30:47] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:48] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/! HTTP/1.1" 404 None
[2024-08-10 12:30:48] [tests.test_objects_endpoint] [INFO] - Checking if status code is 404
[2024-08-10 12:30:48] [tests.test_objects_endpoint] [INFO] - Checking if error message is present in response body
[2024-08-10 12:30:48] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_invalid_resource_from_valid_endpoint[!] -- PASSED --
[2024-08-10 12:30:48] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:49] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/test HTTP/1.1" 404 None
[2024-08-10 12:30:49] [tests.test_objects_endpoint] [INFO] - Checking if status code is 404
[2024-08-10 12:30:49] [tests.test_objects_endpoint] [INFO] - Checking if error message is present in response body
[2024-08-10 12:30:49] [root] [INFO] - tests/test_objects_endpoint.py::TestGetMethod::test_get_invalid_resource_from_valid_endpoint[test] -- PASSED --
[2024-08-10 12:30:49] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:50] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 200 None
[2024-08-10 12:30:50] [tests.test_objects_endpoint] [INFO] - Checking if status code is 201
[2024-08-10 12:30:50] [root] [ERROR] - tests/test_objects_endpoint.py::TestPostMethod::test_post_new_valid_resource failed: self = <tests.test_objects_endpoint.TestPostMethod object at 0x10b93c940>

    def test_post_new_valid_resource(self):
        status_code, response_body = make_post_request(const.OBJECTS_ENDPOINT, json=TestObjects.OBJECT_VALID)
        LOGGER.info(f"Checking if status code is {const.STATUS_CREATED}")
>       assert status_code == const.STATUS_CREATED, f"Unexpected status code: {status_code}"
E       AssertionError: Unexpected status code: 200
E       assert 200 == 201
E        +  where 201 = const.STATUS_CREATED

tests/test_objects_endpoint.py:45: AssertionError
[2024-08-10 12:30:50] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:51] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 200 None
[2024-08-10 12:30:51] [tests.test_objects_endpoint] [INFO] - Checking if status code is 201
[2024-08-10 12:30:51] [root] [ERROR] - tests/test_objects_endpoint.py::TestPostMethod::test_post_new_valid_resource_with_headers failed: self = <tests.test_objects_endpoint.TestPostMethod object at 0x10b93cfa0>

    def test_post_new_valid_resource_with_headers(self):
        headers = {"Content-Type": "application/json", "Custom-Header": "Custom-Value"}
        status_code, response_body = make_post_request(
            const.OBJECTS_ENDPOINT, json=TestObjects.OBJECT_VALID, headers=headers
        )
    
        LOGGER.info(f"Checking if status code is {const.STATUS_CREATED}")
>       assert status_code == const.STATUS_CREATED, f"Unexpected status code: {status_code}"
E       AssertionError: Unexpected status code: 200
E       assert 200 == 201
E        +  where 201 = const.STATUS_CREATED

tests/test_objects_endpoint.py:56: AssertionError
[2024-08-10 12:30:51] [tests.test_objects_endpoint] [INFO] - Creating resource
[2024-08-10 12:30:51] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:52] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 200 None
[2024-08-10 12:30:52] [tests.test_objects_endpoint] [INFO] - Checking if status code is 201
[2024-08-10 12:30:52] [root] [ERROR] - tests/test_objects_endpoint.py::TestPostMethod::test_created_resource_exists failed: self = <tests.test_objects_endpoint.TestPostMethod object at 0x10b93cc10>

    def test_created_resource_exists(self):
        LOGGER.info("Creating resource")
        status_code_post, response_body_post = make_post_request(const.OBJECTS_ENDPOINT, json=TestObjects.OBJECT_VALID)
    
        LOGGER.info(f"Checking if status code is {const.STATUS_CREATED}")
>       assert status_code_post == const.STATUS_CREATED, f"Unexpected status code: {status_code_post}"
E       AssertionError: Unexpected status code: 200
E       assert 200 == 201
E        +  where 201 = const.STATUS_CREATED

tests/test_objects_endpoint.py:65: AssertionError
[2024-08-10 12:30:52] [tests.test_objects_endpoint] [INFO] - Creating resource with payload too big
[2024-08-10 12:30:52] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:53] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 500 None
[2024-08-10 12:30:53] [tests.test_objects_endpoint] [INFO] - Checking if status code is 413
[2024-08-10 12:30:53] [root] [ERROR] - tests/test_objects_endpoint.py::TestPostMethod::test_post_new_resource_payload_too_large failed: self = <tests.test_objects_endpoint.TestPostMethod object at 0x10b8f6790>

    def test_post_new_resource_payload_too_large(self):
        LOGGER.info("Creating resource with payload too big")
        status_code, response_body = make_post_request(
            const.OBJECTS_ENDPOINT, json=TestObjects.OBJECT_VERY_LARGE_PAYLOAD
        )
    
        LOGGER.info(f"Checking if status code is {const.STATUS_PAYLOAD_TOO_LARGE}")
>       assert status_code == const.STATUS_PAYLOAD_TOO_LARGE, f"Unexpected status code: {status_code}"
E       AssertionError: Unexpected status code: 500
E       assert 500 == 413
E        +  where 413 = const.STATUS_PAYLOAD_TOO_LARGE

tests/test_objects_endpoint.py:90: AssertionError
[2024-08-10 12:30:53] [tests.test_objects_endpoint] [INFO] - Creating resource
[2024-08-10 12:30:53] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:54] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "POST /objects HTTP/1.1" 200 None
[2024-08-10 12:30:54] [tests.test_objects_endpoint] [INFO] - Checking if resource was created
[2024-08-10 12:30:54] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:55] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/ff808181913b3faf01913bd7579d0072 HTTP/1.1" 200 None
[2024-08-10 12:30:55] [tests.test_objects_endpoint] [INFO] - Updating resource
[2024-08-10 12:30:55] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:56] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "PUT /objects/ff808181913b3faf01913bd7579d0072 HTTP/1.1" 200 None
[2024-08-10 12:30:56] [tests.test_objects_endpoint] [INFO] - Checking if resource was updated
[2024-08-10 12:30:56] [urllib3.connectionpool] [DEBUG] - Starting new HTTPS connection (1): api.restful-api.dev:443
[2024-08-10 12:30:57] [urllib3.connectionpool] [DEBUG] - https://api.restful-api.dev:443 "GET /objects/ff808181913b3faf01913bd7579d0072 HTTP/1.1" 200 None
[2024-08-10 12:30:57] [root] [INFO] - tests/test_objects_endpoint.py::TestPutMethod::test_put_change_existing_resource -- PASSED --
